# Generated by Django 3.0.7 on 2020-06-27 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название компании')),
                ('contract_number', models.PositiveIntegerField(verbose_name='Номер контракта')),
                ('test', models.BooleanField(verbose_name='Тестовый режим')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('sername', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('telephone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='ServType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название типа услуги')),
                ('unit_of_measure', models.CharField(max_length=50, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуги',
            },
        ),
        migrations.CreateModel(
            name='Spokesman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('sername', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('telephone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clilibapp.Client', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Представитель клиента',
                'verbose_name_plural': 'Представители клиента',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Колчиество услуги')),
                ('offered', models.BooleanField(verbose_name='Заказаная ли услуга?')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clilibapp.Client', verbose_name='Компания')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clilibapp.ServType')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clilibapp.Manager', verbose_name='Ответственный менеджер'),
        ),
    ]
