# Generated by Django 3.0.7 on 2020-07-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clilibapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servtype',
            options={'verbose_name': 'Тип услуги', 'verbose_name_plural': 'Типы услуг'},
        ),
        migrations.RemoveField(
            model_name='spokesman',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='spokesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clilibapp.Spokesman', verbose_name='Представитель клиента'),
        ),
    ]
