# Generated by Django 3.0.7 on 2020-07-15 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clilibapp', '0002_auto_20200714_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
