# Generated by Django 3.0.7 on 2020-07-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clilibapp', '0003_client_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='spokesman',
        ),
        migrations.AddField(
            model_name='spokesman',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clilibapp.Client', verbose_name='Компания'),
        ),
    ]
