# Generated by Django 3.0.7 on 2020-08-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clilibapp', '0005_client_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='orgname',
            field=models.CharField(default='vdc', max_length=50, verbose_name='Название организации в vCloud'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_number',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Номер контракта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='test',
            field=models.BooleanField(default=True, verbose_name='Тестовый режим'),
        ),
    ]
