# Generated by Django 3.0.7 on 2020-08-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clilibapp', '0007_auto_20200811_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='servtype',
            name='short_name',
            field=models.CharField(default='short_name', max_length=50, verbose_name='Краткое название типа услуги'),
            preserve_default=False,
        ),
    ]
